swagger: '2.0'
info:
    title: KokteilideretseptuuriNimekiri
    version: 1.0.0
    description: Help to find cocktail recipes
paths:
    '/recipes/{RecipesID}/':
        get:
            tags:
                - Recipes
            responses:
                '200':
                    description: Returns all details of the given <Recipe>
            summary: Get full details of a <Recipe>
            description: Will return all details of a given <Recipe> based on RecipeID given.
    /recipes:
        get:
            tags:
                - recipes
            responses:
                '200':
                    description: Send 200 when recipe is created in databse.
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            - Margarita
                            - Corpse Reviver
                            - Mojito
                            - Queen Mary
                            - Mint Julep
                            - Pina Colada
            summary: Get all the <Recipes> in API
            description: Return all cocktail recipes that are registered in API
        post:
            parameters:
                -
                    name: body
                    description: The <Recipe> that is to be created.
                    schema:
                        $ref: '#/definitions/new-Recipe'
                    in: body
                    required: true
            responses:
                '201':
                    description: Send 201 when <Recipe> is successfully added to the database
                    schema:
                        $ref: '#/definitions/new-Recipe'
                '400':
                    description: 'Missing some parameter, please review your request data.'
                    schema:
                        $ref: '#/definitions/error'
            summary: Create a new <Recipe> into the app
            description: 'Create a new <Recipe> instance with its required details, for further usage.'
definitions:
    new-Recipe:
        title: Root Type for new-Recipe
        description: ''
        required:
            - Beverage
            - Description
            - Name
        type: object
        properties:
            Name:
                type: string
            Description:
                type: string
            Beverage:
                type: string
        example:
            Name: NewRecipeName
            Description: NewRecipeDescription
            Beverage: NewRecipeBeverage
    error:
        description: ''
        type: object
        example:
            error: Error message
