swagger: '2.0'
info:
    title: KokteilideretseptuuriNimekiri
    version: 1.0.0
    description: Help to find cocktail recipes
paths:
    '/recipes/{RecipesID}/':
        get:
            tags:
                - Recipes
            responses:
                '200':
                    description: Returns all details of the given <Recipe>
            summary: Get full details of a <Recipe>
            description: Will return all details of a given <Recipe> based on RecipeID given.
    /recipes:
        get:
            tags:
                - recipes
            responses:
                '200':
                    description: |
                        Retruns a list of cocktail recipes
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            - Margarita
                            - Corpse Reviver
                            - Mojito
                            - Queen Mary
                            - Mint Julep
                            - Pina Colada
            summary: Get all the <Recipes> in API
            description: Return all cocktail recipes that are registered in API
